GET http://localhost:3000/contacts/2

###
GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "first_name": "Jon",
  "last_name": "Miksis",
  "email": "jmiksis13@gmail.com",
  "phone_number": "603-812-7478",
  "address": "379 Cook Ave, Scotch Plains, NJ 07076"
}